apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: restoreverified-writer
  labels:
    app.kubernetes.io/part-of: openkubes-database-postgresql
    openkubes.ai/adr: adr-platform-032
subjects:
  - kind: Group
    name: oidc:database-restore-verifiers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: restoreverified-writer
  apiGroup: rbac.authorization.k8s.io
