#!/usr/bin/env bash
set -euo pipefail

required=(
  CLUSTER_NAME
  NAMESPACE
  KUBERNETES_VERSION
  CONTROL_PLANE_REPLICAS
  WORKER_REPLICAS
  POD_CIDR
  SERVICE_CIDR
  DNS_DOMAIN_SUFFIX
  INFRA_CLUSTER_SECRET_NAME
  INFRA_CLUSTER_SECRET_NAMESPACE
  CONTROL_PLANE_SERVICE_TYPE
  CONTROL_PLANE_ENDPOINT_IP
  CONTROL_PLANE_ENDPOINT_PORT
  KUBEVIRT_VM_NAMESPACE
  VM_IMAGE_URL
  CONTROL_PLANE_CPU_CORES
  CONTROL_PLANE_MEMORY
  WORKER_CPU_CORES
  WORKER_MEMORY
)

for v in "${required[@]}"; do
  if [[ -z "${!v:-}" ]]; then
    echo "ERROR: missing env: ${v}"
    exit 1
  fi
done

echo "Environment validation successful."
