FROM python:3.13-alpine

RUN addgroup -S openkubes && adduser -S -G openkubes -u 65532 openkubes
WORKDIR /app
COPY app.py /app/app.py
USER 65532:65532
EXPOSE 8080
ENTRYPOINT ["python3", "/app/app.py"]
