#!/usr/bin/env bash
set -Eeuo pipefail

# This script is now the image publication boundary. It never performs a
# registry login or push unless PUBLISH_MODE=publish and the explicit approval
# gate is present. Credentials are accepted only through an inherited FD.
: "${PUBLISH_MODE:=render}"
: "${PUBLISH_REGISTRY:=registry.ok-shared.internal}"
: "${PUBLISH_REPOSITORY:=openkubes/machine/staging/adr039-live}"
: "${IMAGE_REGISTRY:=ok174-build.invalid}"
: "${REGISTRY_USERNAME:=}"
: "${REGISTRY_PASSWORD_FD:=}"
: "${PUBLISH_APPROVED:=no}"
: "${PUBLISH_OUTPUT:=./evidence/published-images.env}"

[[ "$PUBLISH_REGISTRY" == "registry.ok-shared.internal" ]] || {
  echo 'PUBLISH_REGISTRY must be registry.ok-shared.internal' >&2
  exit 2
}
[[ "$PUBLISH_MODE" == render || "$PUBLISH_MODE" == publish ]] || {
  echo 'PUBLISH_MODE must be render or publish' >&2
  exit 2
}

output_dir="$(dirname -- "$PUBLISH_OUTPUT")"
output_base="$(basename -- "$PUBLISH_OUTPUT")"
[[ "$output_base" =~ ^[A-Za-z0-9._-]+$ && "$output_base" != . && "$output_base" != .. ]] || {
  echo 'PUBLISH_OUTPUT must have a safe filename component' >&2
  exit 2
}
[[ -d "$output_dir" ]] || {
  echo "publication output directory does not exist: $output_dir" >&2
  exit 2
}

sources=(
  "${IMAGE_REGISTRY}/developer-workspace-opencode:1.18.33"
  "${IMAGE_REGISTRY}/developer-workspace-codex:0.158.0"
  "${IMAGE_REGISTRY}/developer-workspace-fixture:1"
)
names=(opencode codex fixture)

if [[ "$PUBLISH_MODE" == render ]]; then
  printf '%s\n' 'Registry publication plan (dry-run; no login, push, or cluster access):'
  for i in "${!sources[@]}"; do
    printf '  %s -> %s/%s/%s:ok174-proof\n' "${sources[$i]}" "$PUBLISH_REGISTRY" "$PUBLISH_REPOSITORY" "${names[$i]}"
  done
  printf '%s\n' 'Digest discovery: docker buildx imagetools inspect <published-ref>; emitted refs use :ok174-proof@sha256'
  exit 0
fi

[[ "$PUBLISH_APPROVED" == yes ]] || {
  echo 'publish blocked: set PUBLISH_APPROVED=yes in an attended coordinator invocation' >&2
  exit 2
}
[[ -n "$REGISTRY_USERNAME" ]] || { echo 'publish blocked: REGISTRY_USERNAME is required' >&2; exit 2; }
[[ "$REGISTRY_PASSWORD_FD" =~ ^[0-9]+$ ]] || {
  echo 'publish blocked: REGISTRY_PASSWORD_FD must name an inherited descriptor' >&2
  exit 2
}

docker_config_dir=""
output_tmp=""
cleanup() {
  if [[ -n "$docker_config_dir" && -d "$docker_config_dir" ]]; then
    DOCKER_CONFIG="$docker_config_dir" docker logout "$PUBLISH_REGISTRY" >/dev/null 2>&1 || true
    rm -rf -- "$docker_config_dir"
  fi
  if [[ -n "$output_tmp" && -e "$output_tmp" ]]; then
    rm -f -- "$output_tmp"
  fi
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

docker_config_dir="$(mktemp -d "${TMPDIR:-/tmp}/adr039-docker-config.XXXXXX")"
output_tmp="$(mktemp "${output_dir}/.${output_base}.XXXXXX")"
printf '%s\n' '# Generated by image publication; digest-pinned refs only.' > "$output_tmp"

# The descriptor is never placed in argv, a file, or output. Docker reads the
# secret from stdin and owns its handling. DOCKER_CONFIG is disposable and
# isolated from the operator's persistent config.
export DOCKER_CONFIG="$docker_config_dir"
docker login "$PUBLISH_REGISTRY" --username "$REGISTRY_USERNAME" --password-stdin <&"$REGISTRY_PASSWORD_FD" >/dev/null

for i in "${!sources[@]}"; do
  source_image="${sources[$i]}"
  destination="${PUBLISH_REGISTRY}/${PUBLISH_REPOSITORY}/${names[$i]}:ok174-proof"
  docker image inspect "$source_image" >/dev/null
  docker tag "$source_image" "$destination"
  docker push "$destination" >/dev/null
  digest="$(docker buildx imagetools inspect --format '{{.Manifest.Digest}}' "$destination")"
  [[ "$digest" =~ ^sha256:[0-9a-f]{64}$ ]] || {
    echo "digest discovery failed for ${names[$i]}" >&2
    exit 2
  }
  variable="OK174_$(printf '%s' "${names[$i]}" | tr '[:lower:]' '[:upper:]')_IMAGE"
  pinned="${destination}@${digest}"
  printf '%s=%s\n' "$variable" "$pinned" >> "$output_tmp"
  printf '{"name":"%s","image":"%s"}\n' "${names[$i]}" "$pinned"
done
mv -f -- "$output_tmp" "$PUBLISH_OUTPUT"
output_tmp=""
