#!/usr/bin/env python3
"""Keep the XRD's spec schema equal to the reviewed DeveloperWorkspace contract schema.

The contract (ADR-Platform-039) is a JSON Schema draft-07 document. A Kubernetes structural
schema cannot express every draft-07 keyword, so this converts it with a fixed, reviewable set
of rules and fails if xrd.yaml drifts from the conversion:
  - `$ref` into `definitions` is inlined;
  - `const` becomes a one-value `enum`;
  - `enum`-only nodes get the `type` of their values;
  - `uniqueItems: true` on a string array becomes `x-kubernetes-list-type: set`;
  - `additionalProperties: false` is dropped (Kubernetes prunes unknown fields).
Cross-field rules from the spike's validate_input() are carried as CEL x-kubernetes-validations.

Usage: xrd_schema.py --check | --write
"""
import argparse, copy, json, sys
from pathlib import Path
import yaml

HERE = Path(__file__).resolve().parent
CAPABILITY = HERE.parent
REPO = CAPABILITY.parents[3]
CONTRACT = REPO / 'architecture/spikes/ADR-Platform-039/developer-workspace-v0alpha1.schema.json'
XRD = CAPABILITY / 'xrd.yaml'

CEL_RULES = [
    {'rule': "self.lifecycle.profile != 'persistent' || (self.storage.mode == 'persistent' && self.lifecycle.deletion == 'explicit')",
     'message': 'persistent lifecycle requires persistent storage and explicit deletion'},
    {'rule': "self.lifecycle.profile != 'ephemeral' || (self.storage.mode == 'ephemeral' && self.lifecycle.deletion == 'after-retention' && self.lifecycle.evidence.exportBeforeCleanup)",
     'message': 'ephemeral lifecycle requires ephemeral storage, retention cleanup and evidence export'},
]

def convert(node, definitions):
    if '$ref' in node:
        return convert(definitions[node['$ref'].rsplit('/', 1)[1]], definitions)
    out = {}
    for key, value in node.items():
        if key in ('additionalProperties', '$schema', 'definitions'):
            continue
        if key == 'const':
            out['enum'] = [value]
        elif key == 'properties':
            out['properties'] = {name: convert(child, definitions) for name, child in value.items()}
        elif key == 'items':
            out['items'] = convert(value, definitions)
        elif key == 'uniqueItems':
            continue
        else:
            out[key] = copy.deepcopy(value)
    if 'type' not in out and 'enum' in out:
        kinds = {type(v) for v in out['enum']}
        if kinds == {str}: out['type'] = 'string'
        elif kinds == {bool}: out['type'] = 'boolean'
        else: raise ValueError(f'cannot type enum {out["enum"]}')
    if node.get('uniqueItems') is True:
        if out.get('items', {}).get('type') != 'string':
            raise ValueError('uniqueItems is only converted for string arrays')
        out['x-kubernetes-list-type'] = 'set'
    return out

def expected_spec():
    contract = json.loads(CONTRACT.read_text())
    spec = convert(contract['properties']['spec'], contract.get('definitions', {}))
    spec['x-kubernetes-validations'] = CEL_RULES
    return spec

def xrd_document():
    return {
        'apiVersion': 'apiextensions.crossplane.io/v2',
        'kind': 'CompositeResourceDefinition',
        'metadata': {'name': 'developerworkspaces.workspace.openkubes.io'},
        'spec': {
            'group': 'workspace.openkubes.io',
            # A workspace owns a whole Namespace, so the XR is cluster-scoped like a Namespace.
            'scope': 'Cluster',
            'names': {'kind': 'DeveloperWorkspace', 'plural': 'developerworkspaces'},
            'defaultCompositionRef': {'name': 'developerworkspace-namespace.workspace.openkubes.io'},
            'defaultCompositionUpdatePolicy': 'Manual',
            'versions': [{
                'name': 'v0alpha1', 'served': True, 'referenceable': True,
                'schema': {'openAPIV3Schema': {
                    'type': 'object',
                    'required': ['spec'],
                    'properties': {
                        'spec': expected_spec(),
                        'status': {
                            'type': 'object',
                            'description': 'Written by the composition from observed composed resources.',
                            'properties': {
                                'namespace': {'type': 'string'},
                                'lifecyclePhase': {'type': 'string', 'enum': ['pending', 'running']},
                            },
                        },
                    },
                }},
            }],
        },
    }

HEADER = """# DeveloperWorkspace XRD (OK-175, ADR-Platform-039).
#
# GENERATED by tests/xrd_schema.py from the reviewed contract schema
# architecture/spikes/ADR-Platform-039/developer-workspace-v0alpha1.schema.json.
# Do not edit by hand: run `make xrd` and review the diff; `make xrd-check` fails on drift.
# The contract document itself is the composite resource, so a portable DeveloperWorkspace
# applies unchanged.
"""

def main():
    parser = argparse.ArgumentParser(); mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--check', action='store_true'); mode.add_argument('--write', action='store_true')
    args = parser.parse_args()
    expected = xrd_document()
    if args.write:
        XRD.write_text(HEADER + yaml.safe_dump(expected, sort_keys=False, width=1000)); print(f'WROTE {XRD.name}'); return 0
    actual = yaml.safe_load(XRD.read_text())
    if actual != expected:
        print('FAIL xrd.yaml differs from the conversion of the contract schema; run make xrd', file=sys.stderr); return 1
    print('PASS xrd.yaml matches the contract schema conversion'); return 0

if __name__ == '__main__':
    raise SystemExit(main())
