services:
  capi-platform-runner:
    build:
      context: .
      dockerfile: runner/Dockerfile
    image: kubernautslabs/capi-platform-runner:v4.2
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ${HOME}/.kube/config:/kubeconfig:ro
    environment:
      KUBECONFIG: /kubeconfig
      MGMT_KUBECONFIG: /kubeconfig
    stdin_open: true
    tty: true
