#!/usr/bin/env python3
"""
OK-129 access profile renderer.

One declarative config decides what a standalone kagent installation is allowed
to do. This script turns that config into the Helm value fragment and the
Kubernetes objects that implement it, so the permission model has exactly one
editable source instead of being spread across a chart, a Makefile and three
hand-maintained manifests.

Design rules, in order of importance:

1.  RBAC is the boundary. The tool identity's Role decides what can happen;
    ``toolNames`` and ``requireApproval`` shape *intent*, not permission. The
    renderer therefore never emits a write tool without emitting the matching,
    scoped Role in the same run.
2.  Fail closed. Any config the renderer does not fully understand is an error,
    not a default. Secrets, RBAC objects, ServiceAccounts and wildcards can not
    be granted at all.
3.  Read-only means nothing is generated for the write path. Switching the mode
    back removes objects rather than leaving them orphaned.

Usage::

    render-access.py --config access-config.yaml --out .access.local
    render-access.py --config access-config.yaml --out .access.local --summary

Outputs, all inside ``--out``::

    values-access.yaml        Helm values fragment for the built-in read path
    tools-values.yaml         Helm values for the scoped write tool server
    manifests/10-namespace.yaml
    manifests/20-rbac.yaml
    manifests/30-tool-server.yaml
    manifests/40-agent.yaml
    SUMMARY.md                what this profile grants, in prose

Only ``manifests/`` is meant for ``kubectl apply -f``. Nothing written here is
private, but it is generated: keep it out of Git and regenerate instead.

Python 3.9+, PyYAML (already required by ok-cluster/render.py).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

# --------------------------------------------------------------------------- #
# Policy tables — the hard limits of what this renderer will ever grant.
# --------------------------------------------------------------------------- #

READ_VERBS = ["get", "list", "watch"]
WRITE_VERBS = ["create", "update", "patch", "delete"]

#: Resources a write profile may target: name -> (apiGroup, extra verbs).
#: Pods deliberately get no ``create``: an agent restarts a workload by deleting
#: a Pod or patching its controller, it does not hand-build Pods.
WRITABLE_RESOURCES = {
    "configmaps": ("", WRITE_VERBS),
    "deployments": ("apps", WRITE_VERBS),
    "statefulsets": ("apps", WRITE_VERBS),
    "daemonsets": ("apps", WRITE_VERBS),
    "replicasets": ("apps", ["update", "patch", "delete"]),
    "services": ("", WRITE_VERBS),
    "ingresses": ("networking.k8s.io", WRITE_VERBS),
    "jobs": ("batch", WRITE_VERBS),
    "cronjobs": ("batch", WRITE_VERBS),
    "pods": ("", ["delete"]),
}

#: Never grantable, whatever the config says. Secrets and the RBAC objects are
#: the privilege-escalation path; the rest is cluster infrastructure that an
#: application-level agent has no business changing.
FORBIDDEN_RESOURCES = {
    "*",
    "secrets",
    "serviceaccounts",
    "roles",
    "rolebindings",
    "clusterroles",
    "clusterrolebindings",
    "namespaces",
    "nodes",
    "persistentvolumes",
    "customresourcedefinitions",
    "validatingwebhookconfigurations",
    "mutatingwebhookconfigurations",
}

#: Read-only context every write profile gets inside its own scope, so the agent
#: can verify the change it just made instead of asserting success.
WRITE_SCOPE_CONTEXT = [
    ("", ["pods", "pods/log", "events"], READ_VERBS),
    ("apps", ["replicasets"], READ_VERBS),
]

PROTECTED_NAMESPACE_PREFIXES = ("kube-",)

DNS_LABEL = re.compile(r"^[a-z0-9]([-a-z0-9]*[a-z0-9])?$")

DEFAULT_WRITE_TOOLS = [
    "k8s_apply_manifest",
    "k8s_patch_resource",
    "k8s_delete_resource",
]

DEFAULT_READ_TOOLS = [
    "k8s_get_resources",
    "k8s_describe_resource",
    "k8s_get_events",
    "k8s_get_pod_logs",
    "k8s_get_resource_yaml",
]

COMMON_LABELS = {
    "app.kubernetes.io/part-of": "kagent-standalone",
    "app.kubernetes.io/managed-by": "render-access.py",
    "openkubes.io/ticket": "OK-129",
}

GENERATED_HEADER = (
    "# Generated by platform/ai/kagent-standalone/access/render-access.py\n"
    "# Source of truth: access-config.yaml. Do not edit this file — edit the\n"
    "# config and re-render, otherwise the next render silently reverts you.\n"
)


class ConfigError(Exception):
    """Raised for any config the renderer refuses to act on."""


# --------------------------------------------------------------------------- #
# Config loading and validation
# --------------------------------------------------------------------------- #


def _require_namespace_name(value: str, field: str) -> str:
    if not isinstance(value, str) or not DNS_LABEL.match(value) or len(value) > 63:
        raise ConfigError(f"{field}: {value!r} is not a valid namespace name")
    return value


def load_config(path: Path, quiet: bool = False) -> dict:
    """Parse and validate the access profile. Raises ConfigError on anything odd.

    ``quiet`` suppresses advisory notes only. Warnings about a weakened boundary
    (an ungated write path, ``default`` as a target) are always printed — they
    are the kind of thing an operator must not be able to miss.
    """
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise ConfigError(f"access config not found: {path}")
    except yaml.YAMLError as exc:
        raise ConfigError(f"{path}: invalid YAML: {exc}")

    if not isinstance(raw, dict):
        raise ConfigError(f"{path}: expected a YAML mapping")

    kind = raw.get("kind")
    if kind not in (None, "KagentAccessProfile"):
        raise ConfigError(f"kind: expected KagentAccessProfile, got {kind!r}")

    mode = raw.get("mode")
    if mode not in ("read-only", "read-write"):
        raise ConfigError("mode: must be 'read-only' or 'read-write'")

    install_ns = _require_namespace_name(
        (raw.get("install") or {}).get("namespace", "kagent"), "install.namespace"
    )

    read = raw.get("read") or {}
    read_scope = read.get("scope", "cluster")
    if read_scope != "cluster":
        raise ConfigError(
            "read.scope: only 'cluster' is implemented. Namespaced read scoping "
            "would have to take over the chart's built-in tool RBAC; that is a "
            "separate, testable change — do not fake it here."
        )
    if read.get("secrets", False):
        raise ConfigError(
            "read.secrets: refused. No profile in this deployment may grant "
            "Secret access to a tool identity."
        )

    cfg = {
        "mode": mode,
        "install_namespace": install_ns,
        "read": {"scope": read_scope, "secrets": False, "tools": None},
        "write": None,
    }

    read_tools = read.get("tools")
    if read_tools is None:
        cfg["read"]["tools"] = list(DEFAULT_READ_TOOLS)
    else:
        if not isinstance(read_tools, list) or not read_tools:
            raise ConfigError("read.tools: must be a non-empty list when set")
        cfg["read"]["tools"] = [str(t) for t in read_tools]

    if mode == "read-only":
        if raw.get("write"):
            # Not an error: keeping the write block while switching the mode off
            # is the normal way to park a profile. Say so, do not act on it.
            if not quiet:
                print(
                    "note: mode is read-only — the write block is parsed for "
                    "validation but nothing is generated for it.",
                    file=sys.stderr,
                )
            _validate_write(raw["write"], install_ns)
        return cfg

    write_raw = raw.get("write")
    if not write_raw:
        raise ConfigError("write: required when mode is 'read-write'")
    cfg["write"] = _validate_write(write_raw, install_ns)
    return cfg


def _validate_write(write_raw: object, install_ns: str) -> dict:
    if not isinstance(write_raw, dict):
        raise ConfigError("write: expected a mapping")

    scope = write_raw.get("scope")
    if scope not in ("cluster", "namespaces"):
        raise ConfigError("write.scope: must be 'cluster' or 'namespaces'")

    namespaces = write_raw.get("namespaces") or []
    if not isinstance(namespaces, list):
        raise ConfigError("write.namespaces: expected a list")
    namespaces = [_require_namespace_name(n, "write.namespaces[]") for n in namespaces]

    if scope == "namespaces":
        if not namespaces:
            raise ConfigError(
                "write.namespaces: must list at least one namespace when "
                "write.scope is 'namespaces'"
            )
    elif namespaces:
        raise ConfigError(
            "write.namespaces: must be empty when write.scope is 'cluster'. "
            "Two scopes at once is ambiguous — pick one."
        )

    for ns in namespaces:
        if ns.startswith(PROTECTED_NAMESPACE_PREFIXES):
            raise ConfigError(f"write.namespaces: {ns!r} is a protected namespace")
        if ns == install_ns:
            raise ConfigError(
                f"write.namespaces: {ns!r} is the kagent install namespace. "
                "Letting an agent write into kagent's own namespace means it can "
                "rewrite its own Agent and tool definitions."
            )
        if ns == "default":
            print(
                "warning: write.namespaces includes 'default'. Everything "
                "unqualified lands there; prefer a purpose-named namespace.",
                file=sys.stderr,
            )

    resources = write_raw.get("resources") or []
    if not isinstance(resources, list) or not resources:
        raise ConfigError("write.resources: must list at least one resource")
    resources = [str(r).lower() for r in resources]

    for res in resources:
        if res in FORBIDDEN_RESOURCES:
            raise ConfigError(
                f"write.resources: {res!r} can never be granted by this renderer"
            )
        if res not in WRITABLE_RESOURCES:
            raise ConfigError(
                f"write.resources: {res!r} is not supported. Supported: "
                + ", ".join(sorted(WRITABLE_RESOURCES))
            )

    require_approval = write_raw.get("requireApproval", True)
    if not isinstance(require_approval, bool):
        raise ConfigError("write.requireApproval: must be true or false")
    if not require_approval and scope == "cluster":
        raise ConfigError(
            "write.requireApproval=false with write.scope=cluster is refused: "
            "that is an unattended cluster-wide writer. Narrow the scope or keep "
            "the approval gate."
        )
    if not require_approval:
        print(
            "warning: write.requireApproval is false — writes execute without a "
            "human. Only defensible on a disposable cluster.",
            file=sys.stderr,
        )

    tool_server = write_raw.get("toolServer") or {}
    ts_namespace = _require_namespace_name(
        tool_server.get("namespace", "kagent-write"), "write.toolServer.namespace"
    )
    if ts_namespace in namespaces:
        raise ConfigError(
            f"write.toolServer.namespace: {ts_namespace!r} is also a write "
            "target. Host the tool server outside the namespaces it may change, "
            "otherwise the agent can modify its own tool deployment."
        )
    if ts_namespace == install_ns:
        raise ConfigError(
            "write.toolServer.namespace: must differ from the kagent install "
            "namespace so the write identity stays separately auditable."
        )

    tools = write_raw.get("tools") or DEFAULT_WRITE_TOOLS
    if not isinstance(tools, list) or not tools:
        raise ConfigError("write.tools: must be a non-empty list when set")

    return {
        "scope": scope,
        "namespaces": namespaces,
        "resources": resources,
        "require_approval": require_approval,
        "tool_server_namespace": ts_namespace,
        "tool_server_release": tool_server.get("releaseName", "kagent-write-tools"),
        "tool_server_port": int(tool_server.get("port", 8084)),
        "tool_server_metrics_port": int(tool_server.get("metricsPort", 8085)),
        "tools": [str(t) for t in tools],
        "agent_name": write_raw.get("agentName", "cluster-operator-gated"),
    }


# --------------------------------------------------------------------------- #
# Rule building
# --------------------------------------------------------------------------- #


def build_policy_rules(resources: list[str]) -> list[dict]:
    """Group the requested resources into PolicyRules, one per (apiGroup, verbs)."""
    grouped: dict[tuple[str, tuple[str, ...]], list[str]] = {}
    for res in sorted(resources):
        api_group, extra_verbs = WRITABLE_RESOURCES[res]
        verbs = tuple(READ_VERBS + [v for v in extra_verbs if v not in READ_VERBS])
        grouped.setdefault((api_group, verbs), []).append(res)

    rules = [
        {
            "apiGroups": [api_group],
            "resources": res_list,
            "verbs": list(verbs),
        }
        for (api_group, verbs), res_list in sorted(grouped.items())
    ]

    for api_group, ctx_resources, verbs in WRITE_SCOPE_CONTEXT:
        already = {r for rule in rules if rule["apiGroups"] == [api_group] for r in rule["resources"]}
        missing = [r for r in ctx_resources if r not in already]
        if missing:
            rules.append(
                {"apiGroups": [api_group], "resources": missing, "verbs": list(verbs)}
            )
    return rules


def _labels(extra: dict | None = None) -> dict:
    labels = dict(COMMON_LABELS)
    if extra:
        labels.update(extra)
    return labels


# --------------------------------------------------------------------------- #
# Manifest rendering
# --------------------------------------------------------------------------- #


def render_namespace(write: dict) -> list[dict]:
    return [
        {
            "apiVersion": "v1",
            "kind": "Namespace",
            "metadata": {
                "name": write["tool_server_namespace"],
                "labels": _labels({"openkubes.io/purpose": "kagent-write-tools"}),
            },
        }
    ]


def render_rbac(write: dict) -> list[dict]:
    """Role(s)+RoleBinding(s) per namespace, or one ClusterRole+binding.

    The ServiceAccount is created by the tool-server Helm release, not here. The
    installer asserts that it exists before applying these bindings, so a chart
    that stops creating it fails loudly instead of silently binding nothing.
    """
    rules = build_policy_rules(write["resources"])
    sa_namespace = write["tool_server_namespace"]
    sa_name = write["tool_server_release"]
    subject = {
        "kind": "ServiceAccount",
        "name": sa_name,
        "namespace": sa_namespace,
    }

    if write["scope"] == "cluster":
        return [
            {
                "apiVersion": "rbac.authorization.k8s.io/v1",
                "kind": "ClusterRole",
                "metadata": {"name": sa_name, "labels": _labels()},
                "rules": rules,
            },
            {
                "apiVersion": "rbac.authorization.k8s.io/v1",
                "kind": "ClusterRoleBinding",
                "metadata": {"name": sa_name, "labels": _labels()},
                "roleRef": {
                    "apiGroup": "rbac.authorization.k8s.io",
                    "kind": "ClusterRole",
                    "name": sa_name,
                },
                "subjects": [subject],
            },
        ]

    objects: list[dict] = []
    for namespace in write["namespaces"]:
        objects.append(
            {
                "apiVersion": "rbac.authorization.k8s.io/v1",
                "kind": "Role",
                "metadata": {
                    "name": sa_name,
                    "namespace": namespace,
                    "labels": _labels(),
                },
                "rules": rules,
            }
        )
        objects.append(
            {
                "apiVersion": "rbac.authorization.k8s.io/v1",
                "kind": "RoleBinding",
                "metadata": {
                    "name": sa_name,
                    "namespace": namespace,
                    "labels": _labels(),
                },
                "roleRef": {
                    "apiGroup": "rbac.authorization.k8s.io",
                    "kind": "Role",
                    "name": sa_name,
                },
                "subjects": [subject],
            }
        )
    return objects


def render_tool_server(cfg: dict) -> list[dict]:
    write = cfg["write"]
    url = (
        f"http://{write['tool_server_release']}."
        f"{write['tool_server_namespace']}:{write['tool_server_port']}/mcp"
    )
    return [
        {
            "apiVersion": "kagent.dev/v1alpha2",
            "kind": "RemoteMCPServer",
            "metadata": {
                "name": write["tool_server_release"],
                "namespace": cfg["install_namespace"],
                "labels": _labels(),
            },
            "spec": {
                "description": (
                    "Scoped Kubernetes write tools for the OK-129 access profile "
                    f"({_scope_phrase(write)})."
                ),
                "protocol": "STREAMABLE_HTTP",
                "url": url,
            },
        }
    ]


def _scope_phrase(write: dict) -> str:
    if write["scope"] == "cluster":
        return "cluster-wide"
    if len(write["namespaces"]) == 1:
        return f"namespace {write['namespaces'][0]}"
    return "namespaces " + ", ".join(write["namespaces"])


def _system_message(cfg: dict) -> str:
    write = cfg["write"]
    resources = ", ".join(sorted(write["resources"]))

    if write["scope"] == "cluster":
        scope_rules = [
            "You may operate in any namespace, but only on the resource kinds "
            "listed below. Name the namespace explicitly in every change.",
        ]
    else:
        allowed = ", ".join(write["namespaces"])
        scope_rules = [
            f"You may operate only in these namespaces: {allowed}.",
            "Never operate in another namespace, even if asked directly.",
        ]

    approval_rule = (
        "The tool approval gate is the confirmation. If a request is "
        "unambiguous, do not ask for a separate confirmation."
        if write["require_approval"]
        else "Writes are NOT gated by a human in this profile. Treat every "
        "change as irreversible and state what you are about to do first."
    )

    lines = [
        "You diagnose and repair Kubernetes workloads within a fixed permission "
        "boundary.",
        "",
        "Rules:",
    ]
    lines += [f"- {rule}" for rule in scope_rules]
    lines += [
        f"- You may change only these resource kinds: {resources}.",
        "- Never request or access Secrets. Your identity cannot read them; do "
        "not try.",
        "- Prefer patching an existing object over replacing it, and prefer the "
        "smallest reversible change.",
        "- Before a write, state the target namespace, kind, name, and the "
        "expected result.",
        f"- {approval_rule}",
        "- If a name, namespace, or value is ambiguous, use ask_user.",
        "- If a tool call is rejected, acknowledge the rejection and do not "
        "retry it or ask for approval again.",
        "- After a write, verify the result with a read tool. If a rollout does "
        "not become healthy, report the evidence and stop instead of making "
        "another speculative change.",
        "- If a tool reports a permission error, stop and report it. Never try "
        "to work around the restriction.",
    ]
    return "\n".join(lines) + "\n"


def render_agent(cfg: dict) -> list[dict]:
    write = cfg["write"]
    write_tool = {
        "type": "McpServer",
        "mcpServer": {
            "apiGroup": "kagent.dev",
            "kind": "RemoteMCPServer",
            "name": write["tool_server_release"],
            "toolNames": list(write["tools"]),
        },
    }
    if write["require_approval"]:
        write_tool["mcpServer"]["requireApproval"] = list(write["tools"])

    return [
        {
            "apiVersion": "kagent.dev/v1alpha2",
            "kind": "Agent",
            "metadata": {
                "name": write["agent_name"],
                "namespace": cfg["install_namespace"],
                "labels": _labels(
                    {"openkubes.io/access-scope": write["scope"]}
                ),
            },
            "spec": {
                "description": (
                    f"Workload repairs limited to {_scope_phrase(write)}"
                    + (
                        " — every write needs human approval."
                        if write["require_approval"]
                        else " — UNGATED: writes execute without approval."
                    )
                ),
                "type": "Declarative",
                "declarative": {
                    "runtime": "go",
                    "modelConfig": "default-model-config",
                    "a2aConfig": {},
                    "deployment": {
                        "podSecurityContext": {
                            "runAsNonRoot": True,
                            "runAsUser": 1001,
                            "runAsGroup": 1001,
                            "seccompProfile": {"type": "RuntimeDefault"},
                        },
                        "securityContext": {
                            "allowPrivilegeEscalation": False,
                            "capabilities": {"drop": ["ALL"]},
                        },
                    },
                    "systemMessage": _system_message(cfg),
                    "tools": [
                        {
                            "type": "McpServer",
                            "mcpServer": {
                                "apiGroup": "kagent.dev",
                                "kind": "RemoteMCPServer",
                                "name": "kagent-tool-server",
                                "toolNames": list(cfg["read"]["tools"]),
                            },
                        },
                        write_tool,
                    ],
                },
            },
        }
    ]


def render_read_values(cfg: dict) -> dict:
    """Helm values fragment that pins the built-in tool server to read-only."""
    return {
        "kagent-tools": {
            "enabled": True,
            "tools": {"enabledTools": ["k8s"], "args": ["--read-only"]},
            "rbac": {
                "create": True,
                "readOnly": True,
                "allowSecrets": False,
            },
        }
    }


def render_tools_values(cfg: dict, image_tag: str | None) -> dict:
    """Helm values for the scoped write tool server release.

    ``rbac.create: false`` on purpose: the chart's own RBAC is cluster-wide.
    The scoped Role in ``20-rbac.yaml`` is the whole point of this profile.
    """
    write = cfg["write"]
    values: dict = {
        "fullnameOverride": write["tool_server_release"],
        "tools": {
            "enabledTools": ["k8s"],
            # The chart otherwise renders tools and metrics on the same
            # container port, which Kubernetes rejects as a duplicate port key.
            "metrics": {"port": str(write["tool_server_metrics_port"])},
        },
        "rbac": {"create": False},
        "podSecurityContext": {
            "runAsNonRoot": True,
            "seccompProfile": {"type": "RuntimeDefault"},
        },
        "securityContext": {
            "allowPrivilegeEscalation": False,
            "readOnlyRootFilesystem": True,
            "capabilities": {"drop": ["ALL"]},
        },
    }
    if image_tag:
        values["tools"]["image"] = {"tag": image_tag}
    return values


# --------------------------------------------------------------------------- #
# Summary
# --------------------------------------------------------------------------- #


def render_summary(cfg: dict, config_path: Path) -> str:
    read_tools = ", ".join(f"`{t}`" for t in cfg["read"]["tools"])
    lines = [
        "# Access profile summary",
        "",
        f"Generated from `{config_path.name}`. Regenerate after every change; do",
        "not hand-edit the manifests.",
        "",
        f"**Mode:** `{cfg['mode']}`",
        "",
        "## Read path (always on)",
        "",
        "| Property | Value |",
        "|---|---|",
        "| Identity | the tool server ServiceAccount created by the kagent chart |",
        "| Scope | cluster-wide **read** |",
        "| Secrets | never — `allowSecrets: false` |",
        "| Writes | denied by RBAC, not only by prompt |",
        f"| Tools exposed | {read_tools} |",
        "",
    ]

    if cfg["mode"] == "read-only":
        lines += [
            "## Write path",
            "",
            "Not deployed. No write ServiceAccount, no Role, no write tool server,",
            "and no write Agent exist in this profile. Switching the mode back to",
            "`read-only` removes them again rather than orphaning them.",
            "",
        ]
        return "\n".join(lines)

    write = cfg["write"]
    rules = build_policy_rules(write["resources"])

    if write["scope"] == "cluster":
        rbac_objects = "ClusterRole + ClusterRoleBinding"
    else:
        count = len(write["namespaces"])
        rbac_objects = f"Role + RoleBinding in {count} namespace(s)"
    gate = (
        "yes — every write tool is in requireApproval"
        if write["require_approval"]
        else "**NO — writes execute unattended**"
    )

    lines += [
        "## Write path",
        "",
        "| Property | Value |",
        "|---|---|",
        f"| Identity | `system:serviceaccount:{write['tool_server_namespace']}:{write['tool_server_release']}` |",
        f"| Scope | {_scope_phrase(write)} |",
        f"| RBAC objects | {rbac_objects} |",
        f"| Approval gate | {gate} |",
        "| Secrets | never — not in any generated rule |",
        f"| Write tools | {', '.join(f'`{t}`' for t in write['tools'])} |",
        f"| Agent | `{write['agent_name']}` in `{cfg['install_namespace']}` |",
        "",
        "### Effective permissions",
        "",
        "| apiGroup | Resources | Verbs |",
        "|---|---|---|",
    ]
    for rule in rules:
        group = rule["apiGroups"][0] or "core"
        lines.append(
            f"| `{group}` | {', '.join(rule['resources'])} | {', '.join(rule['verbs'])} |"
        )

    lines += [
        "",
        "### What this profile can NOT do",
        "",
        "- read or write Secrets;",
        "- create or change RBAC objects, ServiceAccounts, Namespaces, Nodes, CRDs",
        "  or webhook configurations;",
        "- act outside the scope above (RBAC denies it — the prompt is not the",
        "  boundary);",
        "- write into the kagent install namespace, so it can not rewrite its own",
        "  Agent or tool definitions.",
        "",
        "Verify, do not trust this table:",
        "",
        "```bash",
        f"SUBJECT='system:serviceaccount:{write['tool_server_namespace']}:{write['tool_server_release']}'",
        "kubectl auth can-i get secrets --all-namespaces --as=\"$SUBJECT\"   # expect no",
        "kubectl auth can-i '*' '*' --all-namespaces --as=\"$SUBJECT\"       # expect no",
    ]
    if write["scope"] == "namespaces":
        target = write["namespaces"][0]
        lines += [
            f"kubectl auth can-i patch deployments -n {target} --as=\"$SUBJECT\"   # expect yes",
            f"kubectl auth can-i patch deployments -n default --as=\"$SUBJECT\"    # expect no",
        ]
    else:
        lines += [
            "kubectl auth can-i patch deployments --all-namespaces --as=\"$SUBJECT\"  # expect yes",
        ]
    lines += ["```", ""]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Output
# --------------------------------------------------------------------------- #


class _BlockDumper(yaml.SafeDumper):
    """SafeDumper that renders multi-line strings as literal blocks.

    Without this, a generated system prompt comes out as a folded single-quoted
    scalar — valid YAML that no human wants to review. These manifests exist to
    be read before they are applied, so readability is a requirement.
    """


def _represent_str(dumper: yaml.Dumper, data: str):
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


_BlockDumper.add_representer(str, _represent_str)


def _dump(objects: list[dict]) -> str:
    return GENERATED_HEADER + yaml.dump_all(
        objects, Dumper=_BlockDumper, default_flow_style=False, sort_keys=False
    )


def _dump_values(values: dict) -> str:
    return GENERATED_HEADER + yaml.dump(
        values, Dumper=_BlockDumper, default_flow_style=False, sort_keys=False
    )


def render_profile_env(cfg: dict) -> str:
    """Shell-sourceable facts about the profile, for the installer.

    The installer must assert the same boundary the renderer generated. Deriving
    that from this file instead of re-parsing YAML in Make keeps one source of
    truth and keeps the Makefile portable.
    """
    write = cfg["write"]
    lines = [
        "# Generated by render-access.py — source, do not edit.",
        f"KAGENT_ACCESS_MODE={cfg['mode']}",
        f"KAGENT_INSTALL_NAMESPACE={cfg['install_namespace']}",
    ]
    if write:
        lines += [
            f"KAGENT_WRITE_SCOPE={write['scope']}",
            'KAGENT_WRITE_NAMESPACES="' + " ".join(write["namespaces"]) + '"',
            f"KAGENT_WRITE_SA_NAMESPACE={write['tool_server_namespace']}",
            f"KAGENT_WRITE_SA_NAME={write['tool_server_release']}",
            f"KAGENT_WRITE_RELEASE={write['tool_server_release']}",
            f"KAGENT_WRITE_AGENT={write['agent_name']}",
            f"KAGENT_WRITE_REQUIRE_APPROVAL={'true' if write['require_approval'] else 'false'}",
            'KAGENT_WRITE_RESOURCES="' + " ".join(sorted(write["resources"])) + '"',
        ]
    else:
        lines += [
            "KAGENT_WRITE_SCOPE=",
            'KAGENT_WRITE_NAMESPACES=""',
            "KAGENT_WRITE_SA_NAMESPACE=",
            "KAGENT_WRITE_SA_NAME=",
            "KAGENT_WRITE_RELEASE=",
            "KAGENT_WRITE_AGENT=",
            "KAGENT_WRITE_REQUIRE_APPROVAL=",
            'KAGENT_WRITE_RESOURCES=""',
        ]
    return "\n".join(lines) + "\n"


def write_outputs(cfg: dict, out_dir: Path, config_path: Path, image_tag: str | None) -> list[Path]:
    manifests_dir = out_dir / "manifests"
    # A stale manifest from a previous, wider profile is a security bug, not
    # clutter: clear the directory before writing.
    if manifests_dir.exists():
        for stale in sorted(manifests_dir.glob("*.yaml")):
            stale.unlink()
    manifests_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []

    def emit(path: Path, content: str) -> None:
        path.write_text(content, encoding="utf-8")
        written.append(path)

    emit(out_dir / "values-access.yaml", _dump_values(render_read_values(cfg)))

    if cfg["mode"] == "read-write":
        emit(manifests_dir / "10-namespace.yaml", _dump(render_namespace(cfg["write"])))
        emit(manifests_dir / "20-rbac.yaml", _dump(render_rbac(cfg["write"])))
        emit(manifests_dir / "30-tool-server.yaml", _dump(render_tool_server(cfg)))
        emit(manifests_dir / "40-agent.yaml", _dump(render_agent(cfg)))
        emit(out_dir / "tools-values.yaml", _dump_values(render_tools_values(cfg, image_tag)))
    else:
        # Leave no usable write values behind in a read-only profile.
        stale_values = out_dir / "tools-values.yaml"
        if stale_values.exists():
            stale_values.unlink()

    emit(out_dir / "profile.env", render_profile_env(cfg))
    emit(out_dir / "SUMMARY.md", render_summary(cfg, config_path))
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Render the kagent standalone access profile (OK-129)."
    )
    parser.add_argument("--config", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument(
        "--tools-image-tag",
        default=None,
        help="Image tag for the scoped write tool server. Pass the pinned "
        "version from the installer so it is not duplicated here.",
    )
    parser.add_argument(
        "--summary",
        action="store_true",
        help="Print the profile summary to stdout as well.",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress the per-file output. Warnings about a weakened boundary "
        "are still printed.",
    )
    args = parser.parse_args(argv)

    try:
        cfg = load_config(args.config, quiet=args.quiet)
    except ConfigError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    written = write_outputs(cfg, args.out, args.config, args.tools_image_tag)

    if not args.quiet:
        print(f"access profile: mode={cfg['mode']}", end="")
        if cfg["write"]:
            print(f", write scope={_scope_phrase(cfg['write'])}", end="")
            if not cfg["write"]["require_approval"]:
                print(" [UNGATED]", end="")
        print()
        for path in written:
            print(f"  wrote {path}")

    if args.summary:
        print()
        print((args.out / "SUMMARY.md").read_text(encoding="utf-8"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
